defaults: &defaults
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
test:
  <<: *defaults
  bucket: <%= ENV['AWS_TEST_BUCKET'] %>
development:
  <<: *defaults
  bucket: <%= ENV['AWS_TEST_BUCKET'] %>
production:
  <<: *defaults
  bucket: <%= ENV['AWS_BUCKET'] %>
